openapi: 3.0.0
info:
  version: 1.0.0
  title: InCare Strategy APIs
  description: Base URL - {STRATEGY_BASE_URL}/strategy/v1

servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Innovaccer/strategy-backend/1.0.0

paths:
  /strategies/search:
    post:
      description: API to fetch list of strategies in the system given set of filters.
      summary: Fetch list of strategies.
      parameters:
        - name: offset
          in: query
          description: Number of strategies to skip.
          schema:
            type: integer
            default: 0
        - name: limit
          in: query
          description: Number of strategies to return.
          schema:
            type: integer
            default: 20
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filters:
                  description: Filters to apply limit search results.
                  type: object
                  properties:
                    name:
                      description: Regex search on strategy name.
                      type: string
                    status:
                      description: Filter on strategy's status.
                      type: array
                      items:
                        type: string
                        enum: [ACTIVE, INACTIVE, DRAFT, DELETED]
                    registryId:
                      description: Filter on strategy's associated Registry.
                      type: string
                    occurrence:
                      description: Filter on strategy types.
                      type: array
                      items:
                        type: string
                        enum:
                          [
                            ADMIT,
                            DISCHARGE,
                            EMERGENCY_ADMIT,
                            EMERGENCY_DISCHARGE,
                            CARE_GAP,
                            POST_ACUTE_CARE,
                            OBSERVATION,
                            CUSTOM,
                          ]
                    activityType:
                      description: Filter of type os assignment activity.
                      type: string
                      enum: [NOTIFICATION, CARE_PROTOCOL]
                    activityId:
                      description: Filter of activity ID. activityType should be explicitly given for this type (NOTIFICATION is not allowed).
                      type: array
                      items:
                        type: string
                    assignmentType:
                      description: Filter on assignment type.
                      type: string
                      enum: [DIRECT, ROSTER]
                sort:
                  description: Key and direction to sort the result set by.
                  type: object
                  properties:
                    key:
                      type: string
                      enum: [name, updatedOn, executionOrder]
                      default: updatedOn
                    direction:
                      type: string
                      enum: [ASC, DESC]
                      default: DESC
      responses:
        200:
          description: List of strategies as per filters provided.
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    description: Pagination Info.
                    type: object
                    properties:
                      previousURL:
                        description: Url for previous page, if applicable.
                        type: string
                      nextURL:
                        description: Url for next page, if applicable.
                        type: string
                      body:
                        description: Body of request, if applicable.
                        type: object
                  count:
                    type: integer
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        executionOrder:
                          type: integer
                        createdOn:
                          type: integer
                        createdBy:
                          type: object
                          properties:
                            id:
                              type: string
                            firstName:
                              type: string
                            middleName:
                              type: string
                            lastName:
                              type: string
                        updatedOn:
                          type: integer
                        updatedBy:
                          type: object
                          properties:
                            id:
                              type: string
                            firstName:
                              type: string
                            middleName:
                              type: string
                            lastName:
                              type: string
                        status:
                          type: string
                          enum: [ACTIVE, INACTIVE, DRAFT, DELETED]
                        occurrence:
                          type: string
                          enum:
                            [
                              ADMIT,
                              DISCHARGE,
                              EMERGENCY_ADMIT,
                              EMERGENCY_DISCHARGE,
                              CARE_GAP,
                              POST_ACUTE_CARE,
                              OBSERVATION,
                              CUSTOM,
                            ]
                        registry:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                        activityType:
                          type: string
                          enum: [NOTIFICATION, CARE_PROTOCOL]
                        activityId:
                          type: string
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Access denied
        500:
          description: Internal server error

  /strategies/count:
    get:
      summary: Count of strategies by status.
      description: API to fetch the count of strategies by status.
      responses:
        200:
          description: Count of strategies.
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  active:
                    type: integer
                  incctive:
                    type: integer
                  draft:
                    type: integer
                  deleted:
                    type: integer
                    
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Access denied
        500:
          description: Internal server error

  /strategies/:
    post:
      summary: Create a new strategy.
      description: Creates a new strategy.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                occurrence:
                  type: string
              required:
                - name
                - occurrence
      responses:
        201:
          description: Strategy that has been created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string